version: "3"

services:

  postgres:
    image: postgres
    restart: always
    container_name: postgres
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong

  kong-ent:
    image: kong-docker-kong-enterprise-edition-internal-preview-docker.bintray.io/kong-enterprise-edition:1.3-alpine
    container_name: kong-ent
    depends_on:
      - postgres
    restart: always
    ports:
      - 8000:8000
      - 8001:8001
      - 8002:8002
      - 8003:8003
      - 8004:8004
      - 8443:8443
      - 8444:8444
      - 8445:8445
      - 8446:8446
      - 8447:8447
    command: "kong start"
    environment:
#      - KONG_ENFORCE_RBAC=on
#      - KONG_ADMIN_GUI_AUTH=openid-connect
#      - KONG_ADMIN_GUI_AUTH_CONF=${KONG_ADMIN_GUI_AUTH_CONF}
#      - KONG_ADMIN_GUI_SESSION_CONF={"secret":"secret","storage":"kong","cookie_secure":false}
      - KONG_AUDIT_LOG=on
      - KONG_LOG_LEVEL=debug
      - KONG_PORTAL_GUI_HOST=localhost:8003
      - KONG_PORTAL_GUI_PROTOCOL=http
      - KONG_PORTAL=on
      - KONG_PORTAL_AUTH=basic-auth
      - KONG_PORTAL_AUTH_CONF={}
#      - KONG_PORTAL_AUTH=openid-connect
      - KONG_PORTAL_AUTO_APPROVE=on
      - KONG_ADMIN_GUI_URL=http://localhost:8002
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=postgres
      - KONG_LICENSE_DATA=${KONG_LICENSE_DATA}
      - KONG_VITALS=on
      - KONG_ANONYMOUS_REPORTS=off
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_PROXY_LISTEN=0.0.0.0:8000, 0.0.0.0:8443 ssl
      - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl
      - KONG_ADMIN_GUI_LISTEN=0.0.0.0:8002, 0.0.0.0:8445 ssl
      - KONG_PORTAL_GUI_LISTEN=0.0.0.0:8003, 0.0.0.0:8446 ssl
      - KONG_PORTAL_API_LISTEN=0.0.0.0:8004, 0.0.0.0:8447 ssl
      - KONG_PORTAL_SESSION_CONF={"cookie_name":"portal_session","secret":"super-secret","cookie_secure":false,"storage":"kong"}
      - KONG_PORTAL_EMAILS_FROM=noreply@konghq.com
      - KONG_PORTAL_EMAILS_REPLY_TO=noreply@konghq.com
      - KONG_SMTP_MOCK=off
      - KONG_SMTP_HOST=smtp.gmail.com
      - KONG_SMTP_PORT=587
      - KONG_SMTP_AUTH_TYPE=plain
      - KONG_SMTP_STARTTLS=on
      - KONG_SMTP_USERNAME=kongemailtest@gmail.com
      - KONG_SMTP_PASSWORD=jNzjktjjzhzwYiQdpd2jymXV
      - KONG_SMTP_ADMIN_EMAILS=noreply@konghq.com

  kong-init:
    image: kong-docker-kong-enterprise-edition-internal-preview-docker.bintray.io/kong-enterprise-edition:1.3-alpine
    container_name: kong-init
    depends_on:
      - postgres
    restart: on-failure:3
    command: "kong migrations bootstrap"
    environment:
      - KONG_PG_HOST=postgres
      - KONG_LICENSE_DATA=${KONG_LICENSE_DATA}
      - KONG_PASSWORD=kong
